### ISSUE TITLE
仓库的代码无法在 Alpine Linux 环境运行，已安装 dotnet 7.0 。下面提供测试环境的 GitHub Actions 代码。

### ISSUE THREAD

**Issue by lvlinkeji** [LagrangeDev/Lagrange.Core#90]
从`https://github.com/LagrangeDev/Lagrange.Core/actions`下载的最新的`Lagrange.OneBot_linux-x64`可以在`Debian`系统运行，但无法在`Alpine` 环境运行。

运行环境为已经安装了`dotnet7-sdk`的`Alpine 3.19.1`的x64系统，错误日志为:
```
Lagrange.OneBot: cannot execute: required file not found
```

甚至无法在安装了`dotnet7-sdk`的`Alpine`环境通过编译，下面是提供测试的`GitHub Actions`代码。直接复制到 `.github/workflows/` 手动运行即可。

```yaml
name: CI

on:

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3

      - uses: jirutka/setup-alpine@v1

      - name: Run script inside Alpine chroot as root
        run: |
          cat /etc/alpine-release
          apk add --no-cache --update --no-progress bash dotnet7-sdk git
          dotnet --info
          git clone https://github.com/LagrangeDev/Lagrange.Core.git
          cd Lagrange.Core
          dotnet publish Lagrange.OneBot/Lagrange.OneBot.csproj \
              -c Release \
              -o out \
              --no-self-contained \
              -p:PublishSingleFile=true \
              -p:IncludeContentInSingleFile=true
        shell: alpine.sh --root {0}
```
